### ISSUE TITLE
Error when player hasn't met all NPCs yet

### ISSUE THREAD

**Issue by Pathoschild** [Bouhm/stardew-valley-mods#26]
If the player hasn't met all NPCs, opening the options page throws an error:
```
[01:45:37 ERROR NPC Map Locations Mod] This mod failed in the InputEvents.ButtonPressed event. Technical details:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NPCMapLocations.MapModMenu..ctor(Int32 x, Int32 y, Int32 width, Int32 height, Boolean[] showSecondaryNPCs, Dictionary`2 customNPCs, Int32 customNpcId, Dictionary`2 markerCrop, Dictionary`2 npcNames) in C:\source\_Stardew\Mods.Bouhm\NPCMapLocations\MapModMenu.cs:line 92
   at NPCMapLocations.MapModMain.HandleInput(GameMenu menu, SButton input) in C:\source\_Stardew\Mods.Bouhm\NPCMapLocations\MapModMain.cs:line 177
   at NPCMapLocations.MapModMain.InputEvents_ButtonPressed(Object sender, EventArgsInput e) in C:\source\_Stardew\Mods.Bouhm\NPCMapLocations\MapModMain.cs:line 167
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 54
```

See [full SMAPI log](https://log.smapi.io/gkvsK4rz).

**Comment by Bouhm** [comment]
_maybe_ fixed in #cf25162?
