### ISSUE TITLE
Getting my console spammed with errors

### ISSUE THREAD

**Issue by MaddoScientisto** [Bouhm/stardew-valley-mods#3]
My console gets spammed with an exception whenever I pause the game, it mentions NPCMapLocations, not sure if there's some conflict with some other mod but it worked fine until it started doing it

```
[11:14:33.157 AM] An exception occured in XNA UpdateTick: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at NPCMapLocations.MapModMain.GameEvents_UpdateTick(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at StardewModdingAPI.Events.GameEvents.InvokeUpdateTick() in Z:\Projects\SMAPI\src\StardewModdingAPI\Events\Game.cs:line 80
```

**Comment by Bouhm** [comment]
Hi, do you have any custom NPC mods installed, or have used any in the past? Also, is this for version 1.41? Thanks.

**Comment by MaddoScientisto** [comment]
I didn't have any custom NPCs installed and it was in version 1.41, it never happened again though so I'm sorry I can't figure out how to reproduce it

**Comment by Bouhm** [comment]
Well, at least it's working for you now :p  
I'm going to leave this issue open in case anyone else has the same problem, and I'll try to investigate it further.
