### ISSUE TITLE
Update check crashes due to 'index out of range' exception

### ISSUE THREAD

**Issue by Pathoschild** [Bouhm/stardew-valley-mods#5]
The update check always fails with this error:
 
> [05:29:38 ERROR SMAPI] Critical app domain exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NPCMapLocations.MapModVersionChecker.<getLatestVersion>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NPCMapLocations.MapModVersionChecker.<getNotification>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

This seems to happen because of this code:

```c#
string tag = (string)json[0]["tag_name"];
return Convert.ToDouble(tag.Split('v')[1]);
```

The problem is that `tag_name` is set to 1.42 (no 'v'), so `tag.Split('v')[1]` crashes with an index-out-of-range error.

(Also, you can make the update check faster by [only fetching the latest release](https://api.github.com/repos/Bouhm/stardew-valley-mods/releases/latest) instead.)

**Comment by Bouhm** [comment]
Thanks for letting me know! :D I made the change so I don't have to do the string splitting but didn't commit my changes until I finished the other stuff.

Also, I cannot emphasize how much you've done for SMAPI and SMAPI modding in general (canimod is no doubt the greatest modding resource out there).
