### ISSUE TITLE
NPC Map Locations 1.43 crashes on launch due to new version format

### ISSUE THREAD

**Issue by Pathoschild** [Bouhm/stardew-valley-mods#7]
NPC Map Locations 1.43 crashes the game on launch because its update check can't handle the mod's new version format. (The error doesn't happen in 1.44.) This seems to be affecting a number of players who haven't updated to the latest version.

Error details:
```
[ERROR SMAPI] Critical app domain exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at NPCMapLocations.MapModVersionChecker.compareVersions(String current, String latest)
   at NPCMapLocations.MapModVersionChecker.<getNotification>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

If you have no objections, I'll mark version 1.43 incompatible. That means SMAPI won't load it, and will instead show an error like this in the console:
>[ERROR SMAPI] Skipped NPC Map Locations v1.43 because this version has an update check error which crashes the game. Please check for a newer version of the mod here:
>\- http://www.nexusmods.com/stardewvalley/mods/239

Let me know if you'd like to change the error text, or if you can fix it on your end somehow. :)

**Comment by Bouhm** [comment]
Yikes, I was hoping I could "ease" into switching to using a different versioning format but I forgot there would still be people using older versions :x 

I would greatly appreciate it if you could mark v1.42 & v1.43 incompatible! Thanks a lot.

**Comment by Pathoschild** [comment]
Done in the upcoming SMAPI 1.6 release. :)

**Comment by Pathoschild** [comment]
PS: SMAPI has a `SemanticVersion` class which lets you compare versions with full support for the [semantic versioning rules](http://semver.org/). It lets you do this:

```cs
ISemanticVersion current = new SemanticVersion("1.4.3-beta");
ISemanticVersion latest = new SemanticVersion("1.4.3");
bool hasUpdate = latest.IsNewerThan(current); // true
```

:)
